server:
  port: 9090

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/streamDB
    username: postgres
    password: root
  mvc:
    log-request-details: true
    pathmatch:
      matching-strategy: ant_path_matcher
  #  main:
  #    allow-circular-references: true
  #    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto : update
    show-sql: true













